export const countriesKeys = [
    "Australia",
    "Austria",
    "Azerbaijan",
    "Albania",
    "Algeria",
    "Angola",
    "Andorra",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Afghanistan",
    "Bahamas",
    "Bangladesh",
    "Barbados",
    "Bahrain",
    "Belize",
    "Belarus",
    "Belgium",
    "Benin",
    "Bulgaria",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Burkina Faso",
    "Burundi",
    "Bhutan",
    "Vanuatu",
    "Vatican City",
    "United Kingdom",
    "Hungary",
    "Venezuela",
    "Timor-Leste",
    "Vietnam",
    "Gabon",
    "Haiti",
    "Guyana",
    "Gambia",
    "Ghana",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Germany",
    "Honduras",
    "Grenada",
    "Greece",
    "Georgia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Egypt",
    "Zambia",
    "Zimbabwe",
    "Israel",
    "India",
    "Indonesia",
    "Jordan",
    "Iraq",
    "Iran",
    "Ireland",
    "Iceland",
    "Spain",
    "Italy",
    "Yemen",
    "Cabo Verde",
    "Kazakhstan",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Qatar",
    "Kenya",
    "Cyprus",
    "Kyrgyzstan",
    "Kiribati",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Cote d'Ivoire",
    "Cuba",
    "Kuwait",
    "Laos",
    "Latvia",
    "Lesotho",
    "Liberia",
    "Lebanon",
    "Libya",
    "Lithuania",
    "Liechtenstein",
    "Luxembourg",
    "Mauritius",
    "Mauritania",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Mali",
    "Maldives",
    "Malta",
    "Morocco",
    "Marshall Islands",
    "Mexico",
    "Mozambique",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niger",
    "Nigeria",
    "Netherlands",
    "Nicaragua",
    "New Zealand",
    "Norway",
    "United Arab Emirates",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Russia",
    "Rwanda",
    "Romania",
    "El Salvador",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "North Macedonia",
    "Seychelles",
    "Senegal",
    "Saint Vincent and the Grenadines",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Serbia",
    "Singapore",
    "Syria",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "Sudan",
    "Suriname",
    "United States",
    "Sierra Leone",
    "Tajikistan",
    "Thailand",
    "Tanzania",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tuvalu",
    "Tunisia",
    "Turkmenistan",
    "Turkey",
    "Uganda",
    "Uzbekistan",
    "Ukraine",
    "Uruguay",
    "Fiji",
    "Philippines",
    "Finland",
    "France",
    "Croatia",
    "Central African Republic",
    "Chad",
    "Montenegro",
    "Czech Republic",
    "Chile",
    "Switzerland",
    "Sweden",
    "Sri Lanka",
    "Ecuador",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Estonia",
    "Ethiopia",
    "South Africa",
    "South Sudan",
    "Jamaica",
    "Japan"
] as const;
