services:
  frontend:
    container_name: frontend-prod
    build:
      context: ../../frontend
      target: prod
#      args:
#        - VITE_CRYPTO_KEY: ${CRYPTO_KEY}
#        - VITE_API_BASE: ${API_BASE}
#    environment:
#      VITE_CRYPTO_KEY: ${CRYPTO_KEY}
#      VITE_API_BASE: ${API_BASE_PROD}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
